version: '3'
services:

  mongo-service:
    image: mongo:3.6
    container_name: mongo
    volumes:
       - /mnt/disks/bmeg/mongo-data:/data/db

  grip-service:
    image: bmeg/grip
    container_name: grip
    # defaults to 8201
    entrypoint: ["grip", "server"]
    depends_on:
      - mongo-service

  nginx-service:
    build: nginx-service
    container_name: nginx
    # use env_file to overwrite env values
    # see GRIP_SERVER
    env_file:
      - nginx.env
    ports:
      - 80:80
      - 443:443
    volumes:
       - /mnt/disks/bmeg/deployment/nginx-service/docker/etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - grip-service

  etl-service:
    build: etl-service
    container_name: etl
    depends_on:
      - grip-service
      - mongo-service
