version: '3'
services:

  mongo:
    image: mongo:3.6
    container_name: mongo
    volumes:
       - /mnt/disks/bmeg/mongo-data:/data/db

  grip:
    image: bmeg/grip
    container_name: grip
    # defaults to 8201
    entrypoint: ["grip", "server"]
    depends_on:
      - mongo

  nginx:
    build: nginx
    container_name: nginx
    # use env_file to overwrite env values
    # see GRIP_SERVER
    env_file:
      - nginx.env
    ports:
      - 80:80
      - 443:443
    volumes:
       - /mnt/disks/bmeg/deployment/nginx/docker/etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - grip

  etl:
    build: etl
    container_name: etl
    # use env_file to overwrite env values
    # see SERVICE_ACCOUNT_EMAIL
    env_file:
      - etl.env    
    volumes:
       - /mnt/disks/bmeg/deployment/service_account.json:/config/service_account.json
    # fuse needs privlidged mode   
    privileged: true   
    depends_on:
      - grip
      - mongo
